# Generated by Django 4.2.9 on 2026-01-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_mono_account_id_recurringtransaction_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='type',
            field=models.CharField(default='bill', max_length=20),
        ),
    ]
